### ISSUE TITLE
FR: adding of extra fields

### ISSUE THREAD

**Issue by markusleming** [edalzell/mailchimp#8]
Great job with the add-on, it's super useful! :)
Not sure if I missed something but if I understand correctly then it only imports the email to MC. Is there a way to also add other fields?

e.g. my forms currently include name, phone and a few custom fields.

Thanks!

**Comment by edalzell** [comment]
Yes, add a Merge field.

<img width="321" alt="2018-01-25 at 2 53 pm" src="https://user-images.githubusercontent.com/6069653/35416823-7e9d7c74-01df-11e8-8877-ae5b8fcc54ac.png">
